<a href="https://colab.research.google.com/github/medoston/computer-vision/blob/main/lab_task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from PIL import Image
import numpy as np


In [3]:
# Load the image and convert it to grayscale
image = Image.open('photo-1575936123452-b67c3203c357.jfif').convert('L')

# Convert the image to a NumPy array
image_array = np.array(image)

# Defining the 2x2 filter
filter = np.array([[1, 1], [1, 1]])

# creating a zeros array to save the output
Conv = np.zeros_like(image_array)

# Apply the filter to the image
for i in range(1, image_array.shape[0]-1):
    for j in range(1, image_array.shape[1]-1):
        Conv[i,j] = np.sum(image_array[i-1:i+1, j-1:j+1] * filter)


print(Conv)

[[  0   0   0 ...   0   0   0]
 [  0  72  74 ... 176 175   0]
 [  0  72  73 ... 164 164   0]
 ...
 [  0  37  41 ... 106 108   0]
 [  0  37  41 ... 110 112   0]
 [  0   0   0 ...   0   0   0]]
